const orders=[
{id:'LUME-855766',iso:'2026-09-22T11:21:00',name:'Wemerson Abreu',email:'cliente@exemplo.com',phone:'(11) 99999-0000',total:79.90,status:'Pagamento confirmado',product:'Calcinha Sensual em Renda',qty:1,address:'Rua Pernambuco, 185 - Casa · Jardim Elizabeth · Mauá/SP · CEP 09335-300',mp:'1790086809467'},
{id:'LUME-381204',iso:'2026-09-22T10:42:00',name:'Marina Costa',email:'marina@exemplo.com',phone:'(11) 98888-1212',total:219.90,status:'Em preparação',product:'Estimulador Premium',qty:1,address:'Av. Central, 410 · São Paulo/SP · CEP 01000-000',mp:'1790081123456'},
{id:'LUME-992731',iso:'2026-09-21T18:10:00',name:'Carlos Lima',email:'carlos@exemplo.com',phone:'(11) 97777-4545',total:299.90,status:'Enviado',product:'Kit Prazer a Dois',qty:1,address:'Rua das Flores, 22 · Osasco/SP · CEP 06000-000',mp:'1790079988221'},
{id:'LUME-640115',iso:'2026-09-21T15:32:00',name:'Ana Souza',email:'ana@exemplo.com',phone:'(11) 96666-7878',total:189.90,status:'Entregue',product:'Vibrador Ponto G Luxo',qty:1,address:'Rua Aurora, 90 · Santo André/SP · CEP 09000-000',mp:'1790074400115'},
{id:'LUME-110284',iso:'2026-09-20T12:18:00',name:'Beatriz Alves',email:'bia@exemplo.com',phone:'(11) 95555-9090',total:139.80,status:'Em preparação',product:'Lubrificante Beijável 100ml',qty:2,address:'Rua Norte, 301 · Diadema/SP · CEP 09900-000',mp:'1790067710284'},
{id:'LUME-784503',iso:'2026-09-19T20:06:00',name:'Rafael Mendes',email:'rafael@exemplo.com',phone:'(11) 94444-2323',total:319.80,status:'Enviado',product:'Estimulador Premium',qty:2,address:'Rua Sul, 15 · Taboão da Serra/SP · CEP 06750-000',mp:'1790059784503'},
{id:'LUME-552901',iso:'2026-09-18T14:20:00',name:'Juliana Rocha',email:'ju@exemplo.com',phone:'(11) 93333-1111',total:249.70,status:'Entregue',product:'Kit Prazer a Dois',qty:2,address:'Rua Bela, 42 · São Paulo/SP',mp:'1790045529011'},
{id:'LUME-447218',iso:'2026-09-17T09:15:00',name:'Paula Nunes',email:'paula@exemplo.com',phone:'(11) 92222-2222',total:99.90,status:'Entregue',product:'Calcinha Sensual em Renda',qty:1,address:'Av. Brasil, 72 · Osasco/SP',mp:'1790034472182'},
{id:'LUME-331087',iso:'2026-09-16T19:44:00',name:'Bruno Reis',email:'bruno@exemplo.com',phone:'(11) 91111-3333',total:459.80,status:'Entregue',product:'Estimulador Premium',qty:2,address:'Rua Azul, 18 · Barueri/SP',mp:'1790023310873'},
{id:'LUME-220615',iso:'2026-09-15T16:05:00',name:'Camila Dias',email:'camila@exemplo.com',phone:'(11) 90000-4444',total:159.80,status:'Entregue',product:'Lubrificante Beijável 100ml',qty:2,address:'Rua Verde, 91 · São Paulo/SP',mp:'1790012206154'}];
const money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}), dt=o=>new Date(o.iso), fmt=o=>dt(o).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}), cls=s=>s==='Pagamento confirmado'?'paid':s==='Em preparação'?'prep':s==='Enviado'?'sent':'done';
let range={from:new Date('2026-09-16T00:00:00'),to:new Date('2026-09-22T23:59:59')};
function inRange(o){let d=dt(o);return d>=range.from&&d<=range.to} function selected(){return orders.filter(inRange)}
function rows(list){return `<div class="row header"><div>Pedido</div><div>Cliente</div><div>Total</div><div>Data</div><div>Status</div><div></div></div>`+(list.length?list.map(o=>`<div class="row"><div><div class="orderid">${o.id}</div><div class="muted">MP ${o.mp}</div></div><div>${o.name}<div class="muted">${o.email}</div></div><div><b>${money(o.total)}</b></div><div>${fmt(o)}</div><div><span class="status ${cls(o.status)}">${o.status}</span></div><div><button class="open" onclick="openOrder('${o.id}')">›</button></div></div>`).join(''):`<div class="no-results">Nenhum pedido encontrado.</div>`)}
function renderDashboard(){const list=selected(), revenue=list.reduce((a,o)=>a+o.total,0), clients=new Set(list.map(o=>o.email)).size, pending=list.filter(o=>o.status!=='Entregue').length, ticket=list.length?revenue/list.length:0;document.querySelector('#metricCards').innerHTML=[['Faturamento',money(revenue),'↗ Receita do período','money'],['Pedidos',list.length,'Vendas confirmadas','orders'],['Ticket médio',money(ticket),'Valor médio por pedido','ticket'],['Clientes',clients,'Compradores no período','clients'],['Pendentes',pending,'Precisam de acompanhamento','pending']].map(x=>`<article><div class="metric-icon ${x[3]}">◆</div><small>${x[0]}</small><strong>${x[1]}</strong><em>${x[2]}</em></article>`).join('');document.querySelector('#chartTotal').textContent=money(revenue);drawRevenue(list);drawStatuses(list);drawBars(list);drawProducts(list);document.querySelector('#recent').innerHTML=rows(orders.slice().sort((a,b)=>dt(b)-dt(a)).slice(0,5));document.querySelector('#orderBadge').textContent=orders.length}
function daysBetween(){let a=new Date(range.from),out=[];a.setHours(0,0,0,0);let end=new Date(range.to);end.setHours(0,0,0,0);while(a<=end&&out.length<31){out.push(new Date(a));a.setDate(a.getDate()+1)}return out}
function daily(list){return daysBetween().map(d=>{let key=d.toISOString().slice(0,10),xs=list.filter(o=>o.iso.slice(0,10)===key);return {d,label:d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'}),value:xs.reduce((a,o)=>a+o.total,0),count:xs.length}})}
function drawRevenue(list){const data=daily(list),svg=document.querySelector('#revenueChart'),max=Math.max(...data.map(x=>x.value),1),W=760,H=260,p=35,pts=data.map((x,i)=>`${p+i*((W-2*p)/Math.max(data.length-1,1))},${H-p-(x.value/max)*(H-2*p)}`).join(' ');let grid=[0,.25,.5,.75,1].map(v=>`<line x1="${p}" y1="${H-p-v*(H-2*p)}" x2="${W-p}" y2="${H-p-v*(H-2*p)}" class="gridline"/>`).join('');let labels=data.map((x,i)=>i%Math.ceil(data.length/7)===0||i===data.length-1?`<text x="${p+i*((W-2*p)/Math.max(data.length-1,1))}" y="252" class="axis">${x.label}</text>`:'').join('');svg.innerHTML=`<defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#ef3d83" stop-opacity=".32"/><stop offset="1" stop-color="#ef3d83" stop-opacity="0"/></linearGradient></defs>${grid}<polygon points="${p},${H-p} ${pts} ${W-p},${H-p}" fill="url(#fill)"/><polyline points="${pts}" class="revline"/>${data.map((x,i)=>x.value?`<circle cx="${p+i*((W-2*p)/Math.max(data.length-1,1))}" cy="${H-p-(x.value/max)*(H-2*p)}" r="4" class="dot"><title>${x.label}: ${money(x.value)}</title></circle>`:'').join('')}${labels}`}
function drawStatuses(list){const defs=[['Pagamento confirmado','paid'],['Em preparação','prep'],['Enviado','sent'],['Entregue','done']],counts=defs.map(([s,c])=>[s,c,list.filter(o=>o.status===s).length]),total=list.length||1,colors=['#ef3d83','#f1b84b','#52a9ea','#58c98a'];let acc=0,stops=counts.map((x,i)=>{let a=acc/total*360;acc+=x[2];return `${colors[i]} ${a}deg ${acc/total*360}deg`}).join(',');document.querySelector('#statusDonut').style.background=`conic-gradient(${stops||'#292326 0deg 360deg'})`;document.querySelector('#donutTotal').textContent=list.length;document.querySelector('#statusLegend').innerHTML=counts.map((x,i)=>`<div><i style="background:${colors[i]}"></i><span>${x[0]}</span><b>${x[2]}</b></div>`).join('')}
function drawBars(list){const data=daily(list),max=Math.max(...data.map(x=>x.count),1);document.querySelector('#ordersBars').innerHTML=data.map(x=>`<div class="bar-col"><b>${x.count||''}</b><div class="bar" style="height:${Math.max(5,x.count/max*120)}px" title="${x.label}: ${x.count} pedido(s)"></div><small>${x.label}</small></div>`).join('')}
function drawProducts(list){let m={};list.forEach(o=>{m[o.product]=(m[o.product]||0)+o.qty});let a=Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,5),max=a[0]?.[1]||1;document.querySelector('#topProducts').innerHTML=a.length?a.map(([n,q],i)=>`<div class="rank"><span class="rankno">0${i+1}</span><div><b>${n}</b><div class="progress"><i style="width:${q/max*100}%"></i></div></div><strong>${q} un.</strong></div>`).join(''):`<div class="no-results">Sem vendas no período.</div>`}
function setRange(days){let to=new Date('2026-09-22T23:59:59'),from=new Date(to);if(days==='month')from=new Date('2026-09-01T00:00:00');else if(days===0)from=new Date('2026-09-22T00:00:00');else{from.setDate(from.getDate()-days+1);from.setHours(0,0,0,0)}range={from,to};syncDates();renderDashboard()}
function syncDates(){document.querySelector('#dateFrom').value=range.from.toISOString().slice(0,10);document.querySelector('#dateTo').value=range.to.toISOString().slice(0,10)}
document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.quick button').forEach(x=>x.classList.remove('active'));b.classList.add('active');setRange(b.dataset.days==='month'?'month':+b.dataset.days)});document.querySelector('#applyDates').onclick=()=>{let f=document.querySelector('#dateFrom').value,t=document.querySelector('#dateTo').value;if(!f||!t)return;range={from:new Date(f+'T00:00:00'),to:new Date(t+'T23:59:59')};document.querySelectorAll('.quick button').forEach(x=>x.classList.remove('active'));renderDashboard()};
function showView(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===id));let names={dashboard:'Visão geral',orders:'Pedidos',customers:'Clientes',products:'Produtos',reports:'Relatórios'};document.getElementById('pageTitle').textContent=names[id]}window.showView=showView;document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function filterOrders(){let q=(document.querySelector('#search').value||'').toLowerCase(),s=document.querySelector('#filter').value,d=document.querySelector('#orderDate').value;let list=orders.filter(o=>(!q||(o.id+' '+o.name+' '+o.email).toLowerCase().includes(q))&&(!s||o.status===s)&&(!d||o.iso.slice(0,10)===d));document.querySelector('#orderList').innerHTML=rows(list)}document.querySelector('#search').oninput=filterOrders;document.querySelector('#filter').onchange=filterOrders;document.querySelector('#orderDate').onchange=filterOrders;document.querySelector('#clearFilters').onclick=()=>{document.querySelector('#search').value='';document.querySelector('#filter').value='';document.querySelector('#orderDate').value='';filterOrders()};
function openOrder(id){const o=orders.find(x=>x.id===id);document.querySelector('#detail').innerHTML=`<p class="muted">${fmt(o)}</p><h2>${o.id}</h2><span class="status ${cls(o.status)}">${o.status}</span><div class="timeline"><i class="on"></i><i class="${o.status!=='Pagamento confirmado'?'on':''}"></i><i class="${['Enviado','Entregue'].includes(o.status)?'on':''}"></i><i class="${o.status==='Entregue'?'on':''}"></i></div><div class="detailbox"><b>Cliente</b><p>${o.name}<br>${o.email}<br>${o.phone}</p></div><div class="detailbox"><b>Pedido</b><p>${o.product}<br>Quantidade: ${o.qty}<br><b>${money(o.total)}</b></p></div><div class="detailbox"><b>Entrega</b><p>${o.address}</p></div><div class="detailbox"><b>Pagamento</b><p>Mercado Pago<br>ID ${o.mp}<br>Status: aprovado</p></div><div class="status-form"><label>Novo status</label><select id="newStatus"><option>Pagamento confirmado</option><option>Em preparação</option><option>Enviado</option><option>Entregue</option></select><button onclick="updateStatus('${o.id}')">Atualizar status</button><span class="hint">Na versão integrada, esta ação salvará no banco e enviará um e-mail automático ao cliente.</span></div>`;document.querySelector('#newStatus').value=o.status;document.querySelector('#drawer').classList.add('show')}window.openOrder=openOrder;
function updateStatus(id){const o=orders.find(x=>x.id===id);o.status=document.querySelector('#newStatus').value;document.querySelector('#drawer').classList.remove('show');renderDashboard();filterOrders();toast('Status atualizado no preview: '+o.status)}window.updateStatus=updateStatus;document.querySelector('#close').onclick=()=>document.querySelector('#drawer').classList.remove('show');document.querySelector('#drawer').onclick=e=>{if(e.target.id==='drawer')e.currentTarget.classList.remove('show')};function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2600)}document.querySelector('#logout').onclick=()=>toast('O login seguro será conectado na próxima etapa.');syncDates();renderDashboard();filterOrders();
