const orders=[
{id:'LUME-855766',date:'22/09/2026 11:21',name:'Wemerson Abreu',email:'cliente@exemplo.com',phone:'(11) 99999-0000',total:79.90,status:'Pagamento confirmado',product:'Calcinha Sensual em Renda',qty:1,address:'Rua Pernambuco, 185 - Casa · Jardim Elizabeth · Mauá/SP · CEP 09335-300',mp:'1790086809467'},
{id:'LUME-381204',date:'22/09/2026 10:42',name:'Marina Costa',email:'marina@exemplo.com',phone:'(11) 98888-1212',total:219.90,status:'Em preparação',product:'Estimulador Premium',qty:1,address:'Av. Central, 410 · São Paulo/SP · CEP 01000-000',mp:'1790081123456'},
{id:'LUME-992731',date:'21/09/2026 18:10',name:'Carlos Lima',email:'carlos@exemplo.com',phone:'(11) 97777-4545',total:299.90,status:'Enviado',product:'Kit Prazer a Dois',qty:1,address:'Rua das Flores, 22 · Osasco/SP · CEP 06000-000',mp:'1790079988221'},
{id:'LUME-640115',date:'21/09/2026 15:32',name:'Ana Souza',email:'ana@exemplo.com',phone:'(11) 96666-7878',total:189.90,status:'Entregue',product:'Vibrador Ponto G Luxo',qty:1,address:'Rua Aurora, 90 · Santo André/SP · CEP 09000-000',mp:'1790074400115'},
{id:'LUME-110284',date:'21/09/2026 12:18',name:'Beatriz Alves',email:'bia@exemplo.com',phone:'(11) 95555-9090',total:139.80,status:'Em preparação',product:'Lubrificante Beijável 100ml',qty:2,address:'Rua Norte, 301 · Diadema/SP · CEP 09900-000',mp:'1790067710284'},
{id:'LUME-784503',date:'20/09/2026 20:06',name:'Rafael Mendes',email:'rafael@exemplo.com',phone:'(11) 94444-2323',total:319.80,status:'Enviado',product:'Algemas em Pelúcia + Estimulador Premium',qty:2,address:'Rua Sul, 15 · Taboão da Serra/SP · CEP 06750-000',mp:'1790059784503'}];
const money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}); const cls=s=>s==='Pagamento confirmado'?'paid':s==='Em preparação'?'prep':s==='Enviado'?'sent':'done';
function rows(list){return `<div class="row header"><div>Pedido</div><div>Cliente</div><div>Total</div><div>Data</div><div>Status</div><div></div></div>`+list.map((o,i)=>`<div class="row"><div><div class="orderid">${o.id}</div><div class="muted">MP ${o.mp}</div></div><div>${o.name}<div class="muted">${o.email}</div></div><div><b>${money(o.total)}</b></div><div>${o.date}</div><div><span class="status ${cls(o.status)}">${o.status}</span></div><div><button class="open" onclick="openOrder('${o.id}')">›</button></div></div>`).join('')}
function render(){document.querySelector('#recent').innerHTML=rows(orders.slice(0,4));filterOrders()}
function showView(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===id));document.getElementById('pageTitle').textContent=id==='dashboard'?'Visão geral':id==='orders'?'Pedidos':'Clientes'}window.showView=showView;
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function filterOrders(){let q=(document.querySelector('#search')?.value||'').toLowerCase(),s=document.querySelector('#filter')?.value||'';let list=orders.filter(o=>(!q||(o.id+' '+o.name+' '+o.email).toLowerCase().includes(q))&&(!s||o.status===s));document.querySelector('#orderList').innerHTML=rows(list)}
document.querySelector('#search').oninput=filterOrders;document.querySelector('#filter').onchange=filterOrders;
function openOrder(id){const o=orders.find(x=>x.id===id);document.querySelector('#detail').innerHTML=`<p class="muted">${o.date}</p><h2>${o.id}</h2><span class="status ${cls(o.status)}">${o.status}</span><div class="detailbox"><b>Cliente</b><p>${o.name}<br>${o.email}<br>${o.phone}</p></div><div class="detailbox"><b>Pedido</b><p>${o.product}<br>Quantidade: ${o.qty}<br><b>${money(o.total)}</b></p></div><div class="detailbox"><b>Entrega</b><p>${o.address}</p></div><div class="status-form"><label>Novo status</label><select id="newStatus"><option>Pagamento confirmado</option><option>Em preparação</option><option>Enviado</option><option>Entregue</option></select><button onclick="updateStatus('${o.id}')">Atualizar status</button><span class="hint">Na versão integrada, esta ação salvará no banco e enviará um e-mail automático ao cliente.</span></div>`;document.querySelector('#newStatus').value=o.status;document.querySelector('#drawer').classList.add('show')}window.openOrder=openOrder;
function updateStatus(id){const o=orders.find(x=>x.id===id);o.status=document.querySelector('#newStatus').value;document.querySelector('#drawer').classList.remove('show');render();toast('Status atualizado no preview: '+o.status)}window.updateStatus=updateStatus;
document.querySelector('#close').onclick=()=>document.querySelector('#drawer').classList.remove('show');document.querySelector('#drawer').onclick=e=>{if(e.target.id==='drawer')e.currentTarget.classList.remove('show')};
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2600)}
document.querySelector('#logout').onclick=()=>toast('O login seguro será conectado na próxima etapa.');render();
