const orders=[
{id:'LUME-855766',date:'22/09/2026 11:21',name:'Wemerson Abreu',email:'cliente@exemplo.com',phone:'(11) 99999-0000',total:79.90,status:'Pagamento confirmado',product:'Calcinha Sensual em Renda',qty:1,address:'Rua Pernambuco, 185 - Casa · Jardim Elizabeth · Mauá/SP · CEP 09335-300',mp:'1790086809467'},
{id:'LUME-381204',date:'22/09/2026 10:42',name:'Marina Costa',email:'marina@exemplo.com',phone:'(11) 98888-1212',total:219.90,status:'Em preparação',product:'Vibrador Ponto G',qty:2,address:'Av. Central, 410 · São Paulo/SP',mp:'1790081123456'},
{id:'LUME-992731',date:'21/09/2026 18:10',name:'Carlos Lima',email:'carlos@exemplo.com',phone:'(11) 97777-4545',total:299.90,status:'Enviado',product:'Kit Erótico Casal',qty:3,address:'Rua das Flores, 22 · Osasco/SP',mp:'1790079988221'},
{id:'LUME-640415',date:'21/09/2026 16:35',name:'Ana Souza',email:'ana@exemplo.com',phone:'(11) 96666-7878',total:59.90,status:'Entregue',product:'Óleo de Massagem 50ml',qty:1,address:'Rua Aurora, 90 · Santo André/SP',mp:'1790074400115'},
{id:'LUME-552913',date:'21/09/2026 14:28',name:'Juliana Mendes',email:'juliana@exemplo.com',phone:'(11) 95555-9090',total:149.80,status:'Pagamento confirmado',product:'Cinta Modeladora',qty:2,address:'Rua Norte, 301 · Diadema/SP',mp:'1790067710284'}];
const products=[['Calcinha Sensual em Renda',32,100],['Vibrador Ponto G',27,84],['Óleo de Massagem 50ml',19,59],['Cinta Modeladora',14,44],['Kit Erótico Casal',11,34]];
const money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});const cls=s=>s==='Pagamento confirmado'?'paid':s==='Em preparação'?'prep':s==='Enviado'?'sent':'done';
function rows(list){return `<div class="row header"><div># Pedido</div><div>Cliente</div><div>Total</div><div>Data</div><div>Status</div><div>Ação</div></div>`+list.map(o=>`<div class="row"><div><div class="orderid">${o.id}</div><div class="muted">MP ${o.mp}</div></div><div>${o.name}<div class="muted">${o.email}</div></div><div><b>${money(o.total)}</b></div><div>${o.date}</div><div><span class="status ${cls(o.status)}">${o.status}</span></div><div><button class="open" onclick="openOrder('${o.id}')">•••</button></div></div>`).join('')}
function render(){document.querySelector('#recent').innerHTML=rows(orders);document.querySelector('#products').innerHTML=products.map((p,i)=>`<div class="product-row"><b>${i+1}</b><div><small>${p[0]}</small><div class="track"><div class="fill" style="width:${p[2]}%"></div></div></div><b>${p[1]}</b></div>`).join('');filterOrders()}
function showView(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(id)?.classList.add('active');document.querySelectorAll('nav button[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===id))}window.showView=showView;document.querySelectorAll('nav button[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function filterOrders(){let q=(document.querySelector('#search')?.value||'').toLowerCase(),s=document.querySelector('#filter')?.value||'';let list=orders.filter(o=>(!q||(o.id+' '+o.name+' '+o.email).toLowerCase().includes(q))&&(!s||o.status===s));if(document.querySelector('#orderList'))document.querySelector('#orderList').innerHTML=rows(list)}document.querySelector('#search').oninput=filterOrders;document.querySelector('#filter').onchange=filterOrders;
function openOrder(id){const o=orders.find(x=>x.id===id);document.querySelector('#detail').innerHTML=`<p class="muted">${o.date}</p><h2>${o.id}</h2><span class="status ${cls(o.status)}">${o.status}</span><div class="detailbox"><b>Cliente</b><p>${o.name}<br>${o.email}<br>${o.phone}</p></div><div class="detailbox"><b>Pedido</b><p>${o.product}<br>Quantidade: ${o.qty}<br><b>${money(o.total)}</b></p></div><div class="detailbox"><b>Entrega</b><p>${o.address}</p></div><div class="status-form"><label>Novo status</label><select id="newStatus"><option>Pagamento confirmado</option><option>Em preparação</option><option>Enviado</option><option>Entregue</option></select><button onclick="updateStatus('${o.id}')">Atualizar status</button><span class="hint">No painel definitivo, a alteração será salva no banco e enviará e-mail ao cliente.</span></div>`;document.querySelector('#newStatus').value=o.status;document.querySelector('#drawer').classList.add('show')}window.openOrder=openOrder;
function updateStatus(id){const o=orders.find(x=>x.id===id);o.status=document.querySelector('#newStatus').value;document.querySelector('#drawer').classList.remove('show');render()}window.updateStatus=updateStatus;document.querySelector('#close').onclick=()=>document.querySelector('#drawer').classList.remove('show');document.querySelector('#drawer').onclick=e=>{if(e.target.id==='drawer')e.currentTarget.classList.remove('show')};render();
