const {randomUUID}=require('crypto');const {db}=require('../lib/db');const CATALOG=require('../lib/catalog');
const money=n=>Number(n).toFixed(2);
module.exports=async(req,res)=>{res.setHeader('Content-Type','application/json; charset=utf-8');if(req.method!=='POST')return res.status(405).json({error:'Método não permitido.'});try{
 const token=(process.env.MP_ACCESS_TOKEN||'').trim();if(!token)throw new Error('MP_ACCESS_TOKEN não configurado.');
 const requested=Array.isArray(req.body?.items)?req.body.items:[],c=req.body?.customer||{},email=String(c.email||'').trim().toLowerCase();
 const required=['name','phone','cep','street','number','district','city','uf'],missing=required.filter(k=>!String(c[k]||'').trim());
 if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)||missing.length)return res.status(400).json({error:'Dados do cliente/entrega incompletos.'});
 let total=0;const items=requested.map(x=>{const p=CATALOG[Number(x.id)],q=Math.max(1,Math.min(20,Number(x.quantity)||1));if(!p)return null;total+=p.unit_price*q;return {title:p.title,quantity:q,unit_price:p.unit_price,total:p.unit_price*q}}).filter(Boolean);total=Math.round(total*100)/100;if(!items.length)return res.status(400).json({error:'Carrinho vazio ou inválido.'});
 const base=(process.env.PUBLIC_BASE_URL||process.env.URL_BASE_PUBLICA||'').trim().replace(/\/$/,'');if(!/^https:\/\//i.test(base))throw new Error('PUBLIC_BASE_URL/URL_BASE_PUBLICA precisa ser HTTPS.');
 const ref=`LUME-${Date.now()}-${randomUUID().slice(0,6).toUpperCase()}`;
 const payload={type:'online',processing_mode:'manual',capture_mode:'automatic_async',total_amount:money(total),external_reference:ref,payer:{email},items:items.map(i=>({title:i.title,quantity:i.quantity,unit_price:money(i.unit_price)})),description:'Compra LUMÉ',config:{statement_descriptor:'LUME',online:{success_url:`${base}/success.html`,failure_url:`${base}/failure.html`,pending_url:`${base}/pending.html`,auto_return:'approved'}}};
 const mp=await fetch('https://api.mercadopago.com/v1/orders',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',Accept:'application/json','X-Idempotency-Key':randomUUID()},body:JSON.stringify(payload)});const data=await mp.json().catch(()=>({}));
 if(!mp.ok)return res.status(mp.status).json({error:'Mercado Pago recusou a criação da order.',details:data.message||data.error||JSON.stringify(data.errors||{})});if(!data.id||!data.checkout_url)throw new Error('Mercado Pago não retornou id/checkout_url.');
 const sql=db();const r=await sql`INSERT INTO orders(order_number,mercado_pago_order_id,customer_name,customer_email,customer_phone,address_zip,address_street,address_number,address_complement,address_neighborhood,address_city,address_state,total_amount,payment_status,payment_method,order_status) VALUES(${ref},${String(data.id)},${String(c.name)},${email},${String(c.phone)},${String(c.cep)},${String(c.street)},${String(c.number)},${String(c.complement||'')},${String(c.district)},${String(c.city)},${String(c.uf)},${total},${String(data.status||'created')},'','aguardando_pagamento') RETURNING id`;
 for(const i of items)await sql`INSERT INTO order_items(order_id,product_name,quantity,unit_price,total_price) VALUES(${r[0].id},${i.title},${i.quantity},${i.unit_price},${i.total})`;
 return res.json({order_id:data.id,checkout_url:data.checkout_url,external_reference:ref,status:data.status});
 }catch(e){console.error('checkout',e);return res.status(500).json({error:'Erro ao iniciar pagamento.',details:e.message});}};
